//Productos
export const MOSTRAR_PRODUCTOS = "MOSTRAR_PRODUCTOS";
export const OCULTAR_PRODUCTOS = "OCULTAR_PRODUCTOS";

export const MOSTRAR_PRODUCTO_ACTUAL = "MOSTRAR_PRODUCTO_ACTUAL";
export const CERRAR_PRODUCTO_ACTUAL = "CERRAR_PRODUCTO_ACTUAL";

//Modal
export const MODAL_ABIERTO = "MODAL_ABIERTO";
export const CERRAR_MODAL = "CERRAR_MODAL";
